export const attendanceConstants = {
    CREATE_ATTENDANCE_REQUEST: 'CREATE_ATTENDANCE_REQUEST',
    CREATE_ATTENDANCE_SUCCESS: 'CREATE_ATTENDANCE_SUCCESS',
    CREATE_ATTENDANCE_FAILURE: 'CREATE_ATTENDANCE_FAILURE',

    CHECKOUT_ATTENDANCE_REQUEST: 'CHECKOUT_ATTENDANCE_REQUEST',
    CHECKOUT_ATTENDANCE_SUCCESS: 'CHECKOUT_ATTENDANCE_SUCCESS',
    CHECKOUT_ATTENDANCE_FAILURE: 'CHECKOUT_ATTENDANCE_FAILURE',

    GET_SHIFT_REQUEST: 'GET_SHIFT_REQUEST',
    GET_SHIFT_SUCCESS: 'GET_SHIFT_SUCCESS',
    GET_SHIFT_FAILED: 'GET_SHIFT_FAILED',

    GET_ATTENDANCE_SUCCESS: 'GET_ATTENDANCE_SUCCESS',
    ALREADY_MARK_ATTENDANCE_SUCCESS: 'ALREADY_MARK_ATTENDANCE_SUCCESS',
    SEARCH_ATTENDANCE_SUCCESS: 'SEARCH_ATTENDANCE_SUCCESS',
        
    CREATE_SHIFT_DETAILS_REQUEST: 'CREATE_SHIFT_DETAILS_REQUEST',
    CREATE_SHIFT_DETAILS_SUCCESS: 'CREATE_SHIFT_DETAILS_SUCCESS',
    CREATE_SHIFT_DETAILS_FAILURE: 'CREATE_SHIFT_DETAILS_FAILURE',

    CREATE_SHIFT_WEEKS_REQUEST: 'CREATE_SHIFT_WEEKS_REQUEST',
    CREATE_SHIFT_WEEKS_SUCCESS: 'CREATE_SHIFT_WEEKS_SUCCESS',
    CREATE_SHIFT_WEEKS_FAILURE: 'CREATE_SHIFT_WEEKS_FAILURE',

    GET_SHIFT_WEEKS_REQUEST: 'GET_SHIFT_WEEKS_REQUEST',
    GET_SHIFT_WEEKS_SUCCESS: 'GET_SHIFT_WEEKS_SUCCESS',
    GET_SHIFT_WEEKS_FAILURE: 'GET_SHIFT_WEEKS_FAILURE',
};