export const hrModuleConstants = {
    GET_HR_LOOKUPS_REQUEST: 'GET_HR_LOOKUPS_REQUEST',
    GET_HR_LOOKUPS_SUCCESS: 'GET_HR_LOOKUPS_SUCCESS',
    GET_HR_LOOKUPS_FAILURE: 'GET_HR_LOOKUPS_FAILURE',

    CREATE_PERSONAL_DETAILS_REQUEST: 'CREATE_PERSONAL_DETAILS_REQUEST',
    CREATE_PERSONAL_DETAILS_SUCCESS: 'CREATE_PERSONAL_DETAILS_SUCCESS',
    CREATE_PERSONAL_DETAILS_FAILURE: 'CREATE_PERSONAL_DETAILS_FAILURE',

    CREATE_COMPANY_DETAILS_REQUEST: 'CREATE_COMPANY_DETAILS_REQUEST',
    CREATE_COMPANY_DETAILS_SUCCESS: 'CREATE_COMPANY_DETAILS_SUCCESS',
    CREATE_COMPANY_DETAILS_FAILURE: 'CREATE_COMPANY_DETAILS_FAILURE',

    GET_GENDERS_LOOKUPS_REQUEST: 'GET_GENDERS_LOOKUPS_REQUEST',
    GET_GENDERS_LOOKUPS_SUCCESS: 'GET_GENDERS_LOOKUPS_SUCCESS',
    GET_GENDERS_LOOKUPS_FAILURE: 'GET_GENDERS_LOOKUPS_FAILURE',

    GET_PERSONAL_DETAILS_REQUEST: 'GET_PERSONAL_DETAILS_REQUEST',
    GET_PERSONAL_DETAILS_SUCCESS: 'GET_PERSONAL_DETAILS_SUCCESS',
    GET_PERSONAL_DETAILS_FAILURE: 'GET_PERSONAL_DETAILS_FAILURE',

    GET_SINGLE_PERSONAL_DETAILS_REQUEST: 'GET_SINGLE_PERSONAL_DETAILS_REQUEST',
    GET_SINGLE_PERSONAL_DETAILS_SUCCESS: 'GET_SINGLE_PERSONAL_DETAILS_SUCCESS',
    GET_SINGLE_PERSONAL_DETAILS_FAILURE: 'GET_SINGLE_PERSONAL_DETAILS_FAILURE',

    CREATE_FAMILY_DETAILS_REQUEST: 'CREATE_FAMILY_DETAILS_REQUEST',
    CREATE_FAMILY_DETAILS_SUCCESS: 'CREATE_FAMILY_DETAILS_SUCCESS',
    CREATE_FAMILY_DETAILS_FAILURE: 'CREATE_FAMILY_DETAILS_FAILURE',

    GET_FAMILY_DETAILS_REQUEST: 'GET_FAMILY_DETAILS_REQUEST',
    GET_FAMILY_DETAILS_SUCCESS: 'GET_FAMILY_DETAILS_SUCCESS',
    GET_FAMILY_DETAILS_FAILURE: 'GET_FAMILY_DETAILS_FAILURE',

};
