export const userConstants = {
    GET_PERMISSIONS_REQUEST: 'GET_PERMISSIONS_REQUEST',
    GET_PERMISSIONS_SUCCESS: 'GET_PERMISSIONS_SUCCESS',
    GET_PERMISSIONS_FAILURE: 'GET_PERMISSIONS_FAILURE',

    GET_NONCPCGR_USER_LOGIN_REQUEST: 'GET_NONCPCGR_USER_LOGIN_REQUEST',
    GET_NONCPCGR_USER_LOGIN_SUCCESS: 'GET_NONCPCGR_USER_LOGIN_SUCCESS',
    GET_NONCPCGR_USER_LOGIN_FAILURE: 'GET_NONCPCGR_USER_LOGIN_FAILURE',

    GET_DEFAULT_CLIENT_REQUEST: 'GET_DEFAULT_CLIENT_REQUEST',
    GET_DEFAULT_CLIENT_SUCCESS: 'GET_DEFAULT_CLIENT_SUCCESS',
    GET_DEFAULT_CLIENT_FAILURE: 'GET_DEFAULT_CLIENT_FAILURE',

    CREATE_PROFILE_REQUEST: 'CREATE_PROFILE_REQUEST',
    CREATE_PROFILE_SUCCESS: 'CREATE_PROFILE_SUCCESS',
    CREATE_PROFILE_FAILURE: 'CREATE_PROFILE_FAILURE',

    CREATE_NONCPCGR_USER_REQUEST: 'CREATE_NONCPCGR_USER_REQUEST',
    CREATE_NONCPCGR_USER_SUCCESS: 'CREATE_NONCPCGR_USER_SUCCESS',
    CREATE_NONCPCGR_USER_FAILURE: 'CREATE_NONCPCGR_USER_FAILURE',

    GET_PROFILE_ID_REQUEST: 'GET_PROFILE_ID_REQUEST',
    GET_PROFILE_ID_SUCCESS: 'GET_PROFILE_ID_SUCCESS',
    GET_PROFILE_ID_FAILURE: 'GET_PROFILE_ID_FAILURE',

    GET_USER_FORGOT_PASSWORD_REQUEST: 'GET_USER_FORGOT_PASSWORD_REQUEST',
    GET_USER_FORGOT_PASSWORD_SUCCESS: 'GET_USER_FORGOT_PASSWORD_SUCCESS',
    GET_USER_FORGOT_PASSWORD_FAILURE: 'GET_USER_FORGOT_PASSWORD_FAILURE',

    GET_USER_CONFIRM_TOKEN_REQUEST: 'GET_USER_CONFIRM_TOKEN_REQUEST',
    GET_USER_CONFIRM_TOKEN_SUCCESS: 'GET_USER_CONFIRM_TOKEN_SUCCESS',
    GET_USER_CONFIRM_TOKEN_FAILURE: 'GET_USER_CONFIRM_TOKEN_FAILURE',
};